// GENERATED by npm run update:prepare. Edit updates/*/releases instead.
export const FRONTEND_VERSION = "1.0.17";
export const FRONTEND_UPDATE_HISTORY = [
  {
    "file": "1.0.17.json",
    "version": "1.0.17",
    "releasedAt": "2026-09-09",
    "required": true,
    "notes": [
      "Presensi Masuk & Pulang kini terkunci pada KAMERA DEPAN; kamera belakang ditolak beserta pesan penjelasannya.",
      "Verifikasi wajah penuh sebelum foto dapat diambil: wajah harus utuh (dahi sampai dagu), menghadap lurus, satu orang, dan tidak tertutup.",
      "Pemeriksaan ulang wajah pada foto yang benar-benar dijepret, sehingga kamera tidak bisa dialihkan sesaat sebelum menjepret.",
      "Pembaruan aplikasi kini dipaksa: HP yang masih memakai versi lama otomatis mendeteksi versi baru di server, membersihkan cache, dan memuat ulang sendiri.",
      "Sisa Service Worker dan Cache Storage dari rilis lama dibersihkan saat aplikasi dibuka, sehingga cukup me-refresh halaman untuk mendapatkan perubahan terbaru."
    ]
  },
  {
    "file": "1.0.16.json",
    "version": "1.0.16",
    "releasedAt": "2026-09-08",
    "required": true,
    "notes": [
      "Lokasi perangkat kini wajib aktif: menu tidak terbuka sebelum GPS terbaca, lengkap dengan panduan pengaktifan per perangkat.",
      "Pelacakan posisi karyawan selama aplikasi terbuka dan Dashboard GPS berpeta untuk admin.",
      "Perbaikan layar putih dan layar update berulang di Safari iOS serta Chrome Android."
    ]
  },
  {
    "file": "1.0.15.json",
    "version": "1.0.15",
    "releasedAt": "2026-08-17",
    "required": true,
    "notes": [
      "Perbaikan geofence, validasi sesi, dan penyegaran tampilan aplikasi mobile."
    ]
  },
  {
    "file": "1.0.14.json",
    "version": "1.0.14",
    "releasedAt": "2026-08-12",
    "required": true,
    "notes": [
      "Performa pembukaan aplikasi ditingkatkan dengan membawa statistik dan pengumuman bersama respons login."
    ]
  }
];
