// GENERATED by npm run update:prepare. Edit updates/*/releases instead.
export const FRONTEND_VERSION = "1.0.16";
export const FRONTEND_UPDATE_HISTORY = [
  {
    "file": "1.0.16.json",
    "version": "1.0.16",
    "releasedAt": "2026-09-08",
    "required": true,
    "notes": [
      "Pelacakan posisi karyawan selama aplikasi terbuka, dengan pemberitahuan saat lokasi dibagikan.",
      "Dashboard GPS berpeta untuk admin: posisi terkini, jejak harian, dan laporan ke Google Sheet.",
      "Perbaikan layar putih dan layar update berulang di Safari iOS serta Chrome Android."
    ]
  },
  {
    "file": "1.0.15.json",
    "version": "1.0.15",
    "releasedAt": "2026-08-17",
    "required": true,
    "notes": [
      "Perbaikan geofence, validasi sesi, dan penyegaran tampilan aplikasi mobile."
    ]
  },
  {
    "file": "1.0.14.json",
    "version": "1.0.14",
    "releasedAt": "2026-08-12",
    "required": true,
    "notes": [
      "Performa pembukaan aplikasi ditingkatkan dengan membawa statistik dan pengumuman bersama respons login."
    ]
  }
];
