// GENERATED by npm run update:prepare. Edit updates/*/releases instead.
export const FRONTEND_VERSION = "1.0.19";
export const FRONTEND_UPDATE_HISTORY = [
  {
    "file": "1.0.19.json",
    "version": "1.0.19",
    "releasedAt": "2026-09-11",
    "required": true,
    "notes": [
      "Satu akun kini hanya aktif di satu perangkat: login dari HP lain otomatis mengakhiri sesi di HP sebelumnya, dengan pesan yang menyebutkan alasannya.",
      "Setiap HP mendapat identitas tetap dan terikat ke akun pemakainya; HP yang dipakai akun lain tercatat dan terlihat di Panel Admin.",
      "Admin dapat menaikkan kuota akun per perangkat, untuk HP milik PIC yang memang mengabsenkan timnya.",
      "Presensi Masuk & Pulang kini mencocokkan wajah dengan wajah acuan karyawan; wajah yang bukan pemilik akun ditolak dan fotonya dibuang.",
      "Pencocokan dilakukan di server — data wajah acuan tidak pernah dikirim ke HP, sehingga tidak dapat ditiru dari sisi aplikasi.",
      "Hasil pencocokan ditampilkan sebelum tombol Kirim ditekan, jadi karyawan tahu lebih awal bila harus mengambil ulang foto.",
      "Model pengenal wajah diunduh di latar saat kamera dibuka, sehingga tidak menambah waktu tunggu sebelum memotret.",
      "Pengajuan Dinas kini terkunci pada kamera depan, tetapi tetap boleh memuat lebih dari satu orang dalam satu foto.",
      "Penolakan Fake GPS pada presensi Masuk & Pulang dikembalikan: koordinat yang tidak bergeser sama sekali pada beberapa pembacaan GPS berbeda kembali menolak kiriman di perangkat."
    ]
  },
  {
    "file": "1.0.18.json",
    "version": "1.0.18",
    "releasedAt": "2026-09-10",
    "required": true,
    "notes": [
      "Sesi kini bertahan 60 menit sejak aktivitas terakhir (sebelumnya 5 menit), sehingga aplikasi yang hanya dibiarkan terbuka tidak lagi keluar sendiri di tengah jam kerja.",
      "Pelacakan posisi tetap berjalan selama aplikasi standby: layar ditahan agar tidak mati sendiri selama pelacakan aktif, dan siklus pengiriman tidak lagi dilewati saat aplikasi berada di latar belakang.",
      "Titik posisi yang gagal terkirim karena sinyal hilang kini disimpan di perangkat dan disusulkan otomatis begitu jaringan kembali, sehingga jejak perjalanan tidak berlubang.",
      "Pesan sesi berakhir menyebutkan durasi yang benar-benar berlaku (sebelumnya selalu tertulis 10 menit).",
      "Perbaikan salah tuduh “Mock GPS”: dua pembacaan GPS yang sebenarnya berasal dari satu fix yang sama (timestamp identik) tidak lagi dianggap sebagai koordinat beku.",
      "Pengambilan sampel lokasi kini memakai watchPosition dan hanya menghitung fix dengan timestamp berbeda, dengan batas waktu 3,5 detik agar form absen tidak menggantung.",
      "Badge merah “Mock GPS” hanya muncul untuk sinyal keras (flag Mock Location dari sistem, mode otomasi, koordinat 0,0, akurasi 0 m, presisi koordinat terlalu rendah)."
    ]
  },
  {
    "file": "1.0.17.json",
    "version": "1.0.17",
    "releasedAt": "2026-09-09",
    "required": true,
    "notes": [
      "Presensi Masuk & Pulang kini terkunci pada KAMERA DEPAN; kamera belakang ditolak beserta pesan penjelasannya.",
      "Verifikasi wajah penuh sebelum foto dapat diambil: wajah harus utuh (dahi sampai dagu), menghadap lurus, satu orang, dan tidak tertutup.",
      "Pemeriksaan ulang wajah pada foto yang benar-benar dijepret, sehingga kamera tidak bisa dialihkan sesaat sebelum menjepret.",
      "Pembaruan aplikasi kini dipaksa: HP yang masih memakai versi lama otomatis mendeteksi versi baru di server, membersihkan cache, dan memuat ulang sendiri.",
      "Sisa Service Worker dan Cache Storage dari rilis lama dibersihkan saat aplikasi dibuka, sehingga cukup me-refresh halaman untuk mendapatkan perubahan terbaru."
    ]
  },
  {
    "file": "1.0.16.json",
    "version": "1.0.16",
    "releasedAt": "2026-09-08",
    "required": true,
    "notes": [
      "Lokasi perangkat kini wajib aktif: menu tidak terbuka sebelum GPS terbaca, lengkap dengan panduan pengaktifan per perangkat.",
      "Pelacakan posisi karyawan selama aplikasi terbuka dan Dashboard GPS berpeta untuk admin.",
      "Perbaikan layar putih dan layar update berulang di Safari iOS serta Chrome Android."
    ]
  },
  {
    "file": "1.0.15.json",
    "version": "1.0.15",
    "releasedAt": "2026-08-17",
    "required": true,
    "notes": [
      "Perbaikan geofence, validasi sesi, dan penyegaran tampilan aplikasi mobile."
    ]
  },
  {
    "file": "1.0.14.json",
    "version": "1.0.14",
    "releasedAt": "2026-08-12",
    "required": true,
    "notes": [
      "Performa pembukaan aplikasi ditingkatkan dengan membawa statistik dan pengumuman bersama respons login."
    ]
  }
];
