#!/usr/bin/env node

/*
 * Menyiapkan satu rilis untuk frontend dan Apps Script.
 * Sumber kebenaran ada di updates/{frontend,backend}/releases/*.json.
 * Jalankan: npm run update:prepare
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const validateOnly = process.argv.includes('--validate-only');
const readJson = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));
const write = (file, content) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content.endsWith('\n') ? content : `${content}\n`);
};

const parseVersion = (version) => {
  const match = String(version || '').match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) throw new Error(`Versi tidak valid: ${version}. Gunakan format x.y.z.`);
  return match.slice(1).map(Number);
};

const compareVersion = (a, b) => {
  const av = parseVersion(a); const bv = parseVersion(b);
  for (let i = 0; i < 3; i += 1) if (av[i] !== bv[i]) return av[i] - bv[i];
  return 0;
};

const loadReleases = (product) => {
  const dir = path.join(root, 'updates', product, 'releases');
  const files = fs.readdirSync(dir).filter((name) => name.endsWith('.json')).sort();
  if (!files.length) throw new Error(`Belum ada release untuk ${product}.`);
  const releases = files.map((name) => ({ file: name, ...readJson(path.join(dir, name)) }));
  const seen = new Set();
  releases.forEach((release) => {
    parseVersion(release.version);
    if (seen.has(release.version)) throw new Error(`Versi duplikat ${product}: ${release.version}`);
    seen.add(release.version);
    if (!release.releasedAt || !Array.isArray(release.notes)) {
      throw new Error(`${product}/${release.file} wajib memiliki releasedAt dan notes.`);
    }
  });
  releases.sort((a, b) => compareVersion(b.version, a.version));
  return releases;
};

const frontend = loadReleases('frontend');
const backend = loadReleases('backend');
const frontendCurrent = frontend[0];
const backendCurrent = backend[0];
if (compareVersion(frontendCurrent.version, backendCurrent.version) !== 0) {
  throw new Error(
    `Versi aktif frontend (${frontendCurrent.version}) dan backend (${backendCurrent.version}) berbeda. ` +
    'Tambahkan release pada kedua folder dengan versi yang sama sebelum build/deploy.'
  );
}

const manifest = {
  frontend: { currentVersion: frontendCurrent.version, history: frontend },
  backend: { currentVersion: backendCurrent.version, history: backend }
};

const backendHistory = JSON.stringify(backend, null, 2);
const codeFile = path.join(root, 'apps-script', 'Code.gs');
const code = fs.readFileSync(codeFile, 'utf8');
const versionPattern = /const APP_VERSION\s*=\s*["'][^"']+["'];/;
if (!versionPattern.test(code)) throw new Error('APP_VERSION tidak ditemukan di apps-script/Code.gs.');
const updatedCode = code.replace(/const APP_VERSION\s*=\s*["'][^"']+["'];/, `const APP_VERSION = "${backendCurrent.version}";`);

if (!validateOnly) {
  write(path.join(root, 'public', 'update-manifest.json'), JSON.stringify(manifest, null, 2));
  write(path.join(root, 'src', 'config', 'updateManifest.js'), `// GENERATED by npm run update:prepare. Edit updates/*/releases instead.\nexport const FRONTEND_VERSION = ${JSON.stringify(frontendCurrent.version)};\nexport const FRONTEND_UPDATE_HISTORY = ${JSON.stringify(frontend, null, 2)};\n`);
  write(path.join(root, 'apps-script', 'UpdateManifest.gs'), `// GENERATED by npm run update:prepare. Edit updates/backend/releases instead.\nvar BACKEND_UPDATE_HISTORY = ${backendHistory};\n`);
  if (updatedCode !== code) write(codeFile, updatedCode);
}

console.log(`Update siap: frontend v${frontendCurrent.version}, backend v${backendCurrent.version}`);
if (!validateOnly) console.log('Berikutnya: npm run build, deploy frontend, lalu salin apps-script/UpdateManifest.gs dan Code.gs ke Apps Script.');
