// GENERATED by npm run update:prepare. Edit updates/backend/releases instead.
var BACKEND_UPDATE_HISTORY = [
  {
    "file": "1.0.17.json",
    "version": "1.0.17",
    "releasedAt": "2026-09-09",
    "required": true,
    "notes": [
      "Penyelarasan versi dengan frontend 1.0.17 (penguncian kamera depan dan verifikasi wajah penuh). Tidak ada perubahan struktur data."
    ]
  },
  {
    "file": "1.0.16.json",
    "version": "1.0.16",
    "releasedAt": "2026-09-08",
    "required": true,
    "notes": [
      "Sheet GpsTracking, GpsPosisiTerakhir, GpsTrackingConfig, dan LaporanGps untuk pemantauan posisi karyawan.",
      "Endpoint pelacakan baru dengan gerbang role: pengiriman posisi untuk semua karyawan, pemantauan khusus admin."
    ]
  },
  {
    "file": "1.0.15.json",
    "version": "1.0.15",
    "releasedAt": "2026-08-17",
    "required": true,
    "notes": [
      "Perbaikan geofence multi-lokasi dan validasi token login."
    ]
  },
  {
    "file": "1.0.14.json",
    "version": "1.0.14",
    "releasedAt": "2026-08-12",
    "required": true,
    "notes": [
      "Optimasi pembacaan statistik dan pengumuman pada proses login."
    ]
  }
];
