// GENERATED by npm run update:prepare. Edit updates/backend/releases instead.
var BACKEND_UPDATE_HISTORY = [
  {
    "file": "1.0.15.json",
    "version": "1.0.15",
    "releasedAt": "2026-08-17",
    "required": true,
    "notes": [
      "Perbaikan geofence multi-lokasi dan validasi token login."
    ]
  },
  {
    "file": "1.0.14.json",
    "version": "1.0.14",
    "releasedAt": "2026-08-12",
    "required": true,
    "notes": [
      "Optimasi pembacaan statistik dan pengumuman pada proses login."
    ]
  }
];
