// GENERATED by npm run update:prepare. Edit updates/backend/releases instead.
var BACKEND_UPDATE_HISTORY = [
  {
    "file": "1.0.23.json",
    "version": "1.0.23",
    "releasedAt": "2026-09-15",
    "required": true,
    "notes": [
      "Potongan import kini idempoten: server mencatat potongan terakhir yang sudah diterapkan (chunkTerakhir), sehingga potongan yang dikirim ulang dijawab sukses tanpa ditulis dua kali.",
      "Potongan yang datang meloncat ditolak dengan kode POTONGAN_LONCAT dan sesi dibersihkan, supaya tidak ada baris yang bolong tanpa disadari.",
      "Sesi import yang sudah selesai menyimpan ringkasannya selama 2 jam, sehingga pengulangan potongan terakhir menjawab ringkasan yang sama alih-alih 'sesi tidak dikenal'.",
      "Catatan sesi import yang basi disapu otomatis saat import baru dimulai, agar Script Properties tidak penuh diam-diam.",
      "Balasan potongan membawa penanda idempoten. Klien hanya mengulang potongan setelah melihat penanda itu, sehingga bundle baru tetap aman menghadapi backend lama — urutan deploy bebas, tetapi tetap ikuti kebiasaan repo ini: frontend dulu, backend belakangan."
    ]
  },
  {
    "file": "1.0.22.json",
    "version": "1.0.22",
    "releasedAt": "2026-09-15",
    "required": true,
    "notes": [
      "Pengecualian gerbang GPS per karyawan, disimpan di Script Properties (GPS_GERBANG_BEBAS) dan diatur dari Panel Admin > Geofence.",
      "Presensi dari karyawan yang dikecualikan diterima tanpa koordinat dan dicatat di Audit GPS dengan keputusan 'DITERIMA-TANPA-LOKASI'. Bila karyawan yang sama mengirim koordinat, pemeriksaan Fake GPS tetap berjalan penuh seperti biasa.",
      "Pengecualian gerbang GPS dan kewajiban geofence tidak dapat dinyalakan bersamaan; kombinasi itu ditolak dengan penjelasan.",
      "Respons login membawa gpsGerbangBebas. Tidak ada sheet baru. Urutan deploy: frontend dulu, backend belakangan."
    ]
  },
  {
    "file": "1.0.21.json",
    "version": "1.0.21",
    "releasedAt": "2026-09-14",
    "required": true,
    "notes": [
      "Login dipercepat: pemeriksaan perangkat pada login harian tidak lagi mengunci seluruh skrip (LockService) dan tidak lagi membaca sheet Devices, DeviceUser, dan SesiAktif secara utuh. Kunci hanya dipakai saat memang ada perangkat atau ikatan baru.",
      "Nomor baris perangkat, ikatan, sesi, dan wajah acuan disimpan sebagai indeks; setiap penulisan tetap memverifikasi isi barisnya lebih dulu sehingga indeks yang basi tidak pernah menimpa baris milik karyawan lain.",
      "Pengumuman aktif ikut disimpan sementara, sehingga sheet Announcements tidak lagi disisir pada setiap login. Pengumuman yang diterbitkan lewat Panel Admin tetap langsung terlihat.",
      "Pembacaan konfigurasi (mode perangkat, mode wajah, ambang, kunci token) tidak lagi diulang di dalam satu permintaan yang sama.",
      "Tidak ada perubahan struktur data maupun kontrak API. Urutan deploy bebas."
    ]
  },
  {
    "file": "1.0.20.json",
    "version": "1.0.20",
    "releasedAt": "2026-09-11",
    "required": true,
    "notes": [
      "Gerbang wajah di handleAbsen (FACE_TIPE_WAJIB) kini juga mencakup tipe Standby, berjalan sebelum foto diunggah ke Drive.",
      "Urutan deploy: bundle frontend 1.0.20 harus tayang lebih dulu — bundle lama mengirim Standby tanpa deskriptor wajah dan akan ditolak pada mode 'ketat'."
    ]
  },
  {
    "file": "1.0.19.json",
    "version": "1.0.19",
    "releasedAt": "2026-09-11",
    "required": true,
    "notes": [
      "Sheet Devices, DeviceUser, SesiAktif, dan DeviceAudit untuk pengikatan perangkat dan pencatatan pelanggarannya.",
      "Token login membawa SessionID; sesi lama otomatis batal saat akun yang sama login di perangkat lain.",
      "Sheet FaceProfiles berisi deskriptor wajah 128 dimensi per karyawan — bukan foto, dan tidak pernah dikirim ke klien.",
      "Gerbang wajah di handleAbsen untuk tipe Hadir & Pulang, berjalan sebelum foto diunggah ke Drive.",
      "Endpoint baru: get_device_list, get_device_audit, save_device_config, lepas_device, cabut_sesi_user, set_device_mode, verifikasi_wajah, get_wajah_list, daftar_wajah, hapus_wajah, set_face_config.",
      "Mode penguncian perangkat dan mode verifikasi wajah dapat diubah dari Panel Admin tanpa menyentuh kode.",
      "Bobot jitter nol dikembalikan ke tingkat memblokir (100), tetapi hanya untuk aplikasi yang melaporkan jumlah fix GPS berbeda; aplikasi versi lama tetap 20 poin agar tidak salah tuduh."
    ]
  },
  {
    "file": "1.0.18.json",
    "version": "1.0.18",
    "releasedAt": "2026-09-10",
    "required": true,
    "notes": [
      "Endpoint track_gps_antrian: menerima titik susulan dari perangkat yang sempat kehilangan sinyal, dalam satu kiriman berisi maksimal 50 titik.",
      "Titik susulan dicatat memakai waktu aslinya di perangkat, sehingga jarak tempuh dan menit di luar area tetap akurat.",
      "Baris posisi terakhir tidak dapat mundur karena titik lama: peta admin hanya diperbarui bila titik yang masuk memang lebih baru.",
      "Bobot sinyal “jitter nol” diturunkan 45 → 20 (WASPADA) karena terbukti menandai karyawan yang perangkatnya hanya diam.",
      "Jitter nol yang muncul bersama riwayat berpola pin Fake GPS mendapat tambahan 30 poin, sehingga kasus manipulasi yang sebenarnya tetap terblokir."
    ]
  },
  {
    "file": "1.0.17.json",
    "version": "1.0.17",
    "releasedAt": "2026-09-09",
    "required": true,
    "notes": [
      "Penyelarasan versi dengan frontend 1.0.17 (penguncian kamera depan dan verifikasi wajah penuh). Tidak ada perubahan struktur data."
    ]
  },
  {
    "file": "1.0.16.json",
    "version": "1.0.16",
    "releasedAt": "2026-09-08",
    "required": true,
    "notes": [
      "Sheet GpsTracking, GpsPosisiTerakhir, GpsTrackingConfig, dan LaporanGps untuk pemantauan posisi karyawan.",
      "Endpoint pelacakan baru dengan gerbang role: pengiriman posisi untuk semua karyawan, pemantauan khusus admin."
    ]
  },
  {
    "file": "1.0.15.json",
    "version": "1.0.15",
    "releasedAt": "2026-08-17",
    "required": true,
    "notes": [
      "Perbaikan geofence multi-lokasi dan validasi token login."
    ]
  },
  {
    "file": "1.0.14.json",
    "version": "1.0.14",
    "releasedAt": "2026-08-12",
    "required": true,
    "notes": [
      "Optimasi pembacaan statistik dan pengumuman pada proses login."
    ]
  }
];
